# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_dispaly.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1369, 602)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resource/tubiao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.99)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video_display = QtWidgets.QLabel(self.centralwidget)
        self.video_display.setGeometry(QtCore.QRect(10, 0, 121, 31))
        self.video_display.setStyleSheet("color:Black;\n"
"font-family:微软雅黑;\n"
"")
        self.video_display.setObjectName("video_display")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 460, 111, 41))
        self.pushButton.setStyleSheet("color:Black;\n"
"font-family:微软雅黑;\n"
"background:rgb(255, 255, 255, 60);\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.pushButton.setObjectName("pushButton")
        self.play_label = QtWidgets.QLabel(self.centralwidget)
        self.play_label.setGeometry(QtCore.QRect(320, 30, 640, 480))
        self.play_label.setStyleSheet("border-width: 1px;\n"
"border-style: solid;\n"
"border-color: #6633FF;\n"
"")
        self.play_label.setFrameShape(QtWidgets.QFrame.Box)
        self.play_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.play_label.setLineWidth(3)
        self.play_label.setMidLineWidth(0)
        self.play_label.setText("")
        self.play_label.setScaledContents(False)
        self.play_label.setObjectName("play_label")
        self.select_player = QtWidgets.QPushButton(self.centralwidget)
        self.select_player.setGeometry(QtCore.QRect(80, 340, 111, 41))
        self.select_player.setStyleSheet("color:Black;\n"
"font-family:微软雅黑;\n"
"background:rgb(255, 255, 255, 60);\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.select_player.setObjectName("select_player")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(80, 400, 111, 41))
        self.start.setStyleSheet("color:Black;\n"
"font-family:微软雅黑;\n"
"background:rgb(255, 255, 255, 60);\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.start.setObjectName("start")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 70, 131, 31))
        self.comboBox.setStyleSheet("color:Black;\n"
"font-family:微软雅黑;\n"
"background:rgb(255, 255, 255, 60);\n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 120, 131, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.push0 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push0.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push0.setObjectName("push0")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.push0)
        self.push2 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push2.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push2.setObjectName("push2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.push2)
        self.push1 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push1.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push1.setObjectName("push1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.push1)
        self.push6 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push6.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push6.setObjectName("push6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.push6)
        self.push7 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push7.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push7.setObjectName("push7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.push7)
        self.push3 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push3.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push3.setObjectName("push3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.push3)
        self.push8 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push8.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push8.setObjectName("push8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.push8)
        self.push4 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push4.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push4.setObjectName("push4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.push4)
        self.push9 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push9.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push9.setObjectName("push9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.push9)
        self.push5 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push5.setStyleSheet("        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 10px;\n"
"        border-color: beige;\n"
"        font: bold 14px;\n"
"        padding: 6px")
        self.push5.setObjectName("push5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.push5)
        self.ksd_view = QtWidgets.QLabel(self.centralwidget)
        self.ksd_view.setGeometry(QtCore.QRect(990, 60, 351, 211))
        self.ksd_view.setStyleSheet("border-width: 1px;\n"
"border-style: solid;\n"
"border-color: #6633FF;\n"
"")
        self.ksd_view.setText("")
        self.ksd_view.setObjectName("ksd_view")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1000, 30, 91, 16))
        self.label.setStyleSheet("color:Black;\n"
"font-family:微软雅黑;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(990, 300, 121, 16))
        self.label_2.setStyleSheet("color:Black;\n"
"font-family:微软雅黑;\n"
"")
        self.label_2.setObjectName("label_2")
        self.current_player = QtWidgets.QLabel(self.centralwidget)
        self.current_player.setGeometry(QtCore.QRect(1100, 330, 121, 161))
        self.current_player.setStyleSheet("border-width: 1px;\n"
"border-style: solid;\n"
"border-color: #6633FF;\n"
"")
        self.current_player.setText("")
        self.current_player.setObjectName("current_player")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.video_display.setText(_translate("MainWindow", "展示系统"))
        self.pushButton.setText(_translate("MainWindow", "开始跟踪"))
        self.select_player.setText(_translate("MainWindow", "选择球员"))
        self.start.setText(_translate("MainWindow", "跟踪器初始化"))
        self.comboBox.setItemText(0, _translate("MainWindow", "    视角  0 - 9"))
        self.comboBox.setItemText(1, _translate("MainWindow", "    视角10 - 19"))
        self.comboBox.setItemText(2, _translate("MainWindow", "    视角20 - 30"))
        self.push0.setText(_translate("MainWindow", "视角0"))
        self.push2.setText(_translate("MainWindow", "视角2"))
        self.push1.setText(_translate("MainWindow", "视角1"))
        self.push6.setText(_translate("MainWindow", "视角6"))
        self.push7.setText(_translate("MainWindow", "视角7"))
        self.push3.setText(_translate("MainWindow", "视角3"))
        self.push8.setText(_translate("MainWindow", "视角8"))
        self.push4.setText(_translate("MainWindow", "视角4"))
        self.push9.setText(_translate("MainWindow", "视角9"))
        self.push5.setText(_translate("MainWindow", "视角5"))
        self.label.setText(_translate("MainWindow", "local frame"))
        self.label_2.setText(_translate("MainWindow", "current player"))
